name: Deploy to kgh

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout StudyKotlin
        uses: actions/checkout@v4
        with:
          fetch-depth: 2

      - name: Clone StudyKotlin repo
        run: |
          # GitHub Actions에서 기본적으로 작업 디렉토리로 체크아웃됨
          git clone --mirror https://github.com/Weedy404/StudyKotlin.git kgh-repo
          
      - name: Debug clone directory
        run: |
          # kgh-repo 디렉토리가 생성되었는지 확인
          ls -al

      - name: Push to kgh
        env:
          GH_PAT: ${{ secrets.GH_PAT }}
        run: |
          cd kgh-repo
          git remote add kgh https://Weedy404:${GH_PAT}@github.com/StudyPS/kgh.git
          git push --force kgh main
