name: Deploy to kgh

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout StudyKotlin
        uses: actions/checkout@v4

      - name: Push to kgh
        env:
          GH_PAT: ${{ secrets.GH_PAT }}
        run: |
          git clone --mirror https://github.com/Weedy404/StudyKotlin.git repo
          cd repo
          git remote add kgh https://Weedy404:${GH_PAT}@github.com/StudyPS/kgh.git
          git push --force kgh main
